const RULES=[
['降息预期','涨',3,'降低持有黄金的机会成本',/降息|鸽派|宽松|rate cuts?|dovish|yields? (?:fall|drop|retreat)/i],
['美元走弱','涨',3,'美元计价黄金获得支撑',/美元(?:下跌|走弱|回落)|dollar (?:falls|weakens|slides)/i],
['央行购金','涨',4,'结构性买盘增加',/央行(?:增持|购买|买入|购金)|central banks? (?:buy|add|boost).{0,20}gold/i],
['避险升温','涨',3,'不确定性推升避险需求',/战争|冲突升级|制裁|地缘政治|衰退|war|conflict escalat|sanctions?|geopolit|recession/i],
['通胀升温','涨',2,'购买力对冲需求可能上升',/通胀(?:上升|升温|超预期|反弹)|inflation (?:rises|heats|accelerates|above)/i],
['加息预期','跌',3,'提高持有黄金的机会成本',/加息|鹰派|紧缩|收益率(?:上涨|上升|走高)|rate hikes?|hawkish|yields? (?:rise|climb|jump)/i],
['降息预期降温','跌',4,'利率可能在高位维持更久',/下调(?:美联储)?降息|推迟降息|rate.?cut (?:bets|odds|expectations) (?:fall|fade)|delay(?:ed)? rate cuts?/i],
['美元走强','跌',3,'美元计价黄金通常承压',/美元(?:上涨|走强)|dollar (?:rises|strengthens|gains)/i],
['风险缓和','跌',3,'避险溢价回落',/停火|和平协议|冲突缓和|软着陆|ceasefire|peace deal|conflict eases|soft landing/i],
['通胀降温','跌',2,'购买力对冲需求减弱',/通胀(?:下降|降温|低于预期)|inflation (?:falls|cools|below)/i]
];
let dataset={items:[],summary:{settled:0,pending:0,neutral:0,hits:0,accuracy:null},predictions:[],updatedAt:null};
function analyse(text){const hits=RULES.filter(r=>r[4].test(text)).map(r=>({label:r[0],direction:r[1],weight:r[2],reason:r[3]}));const up=hits.filter(x=>x.direction==='涨').reduce((s,x)=>s+x.weight,0),down=hits.filter(x=>x.direction==='跌').reduce((s,x)=>s+x.weight,0),score=up-down,total=up+down,strength=total?Math.min(90,Math.round(20+Math.abs(score)/total*48+Math.min(total,12)*1.8)):0;return{hits,up,down,score,direction:score>=0?'涨':'跌',strength}}
function updateSignal(){const r=analyse(document.querySelector('#newsInput').value),dir=document.querySelector('#direction');dir.textContent=r.direction;dir.className=r.direction==='涨'?'up':'down';document.querySelector('#strength').textContent=r.strength;document.querySelector('#scoreline').textContent=`利多 ${r.up.toFixed(1)} 分 · 利空 ${r.down.toFixed(1)} 分`;document.querySelector('#netScore').textContent=`净分 ${r.score>0?'+':''}${r.score.toFixed(1)}`;const box=document.querySelector('#factors');box.innerHTML='';if(!r.hits.length){box.textContent='未命中明确规则，规则强度为 0。';return}r.hits.forEach(h=>{const el=document.createElement('div');el.className='factor';const dot=document.createElement('i');dot.style.background=h.direction==='涨'?'var(--up)':'var(--down)';const body=document.createElement('div');body.innerHTML=`<b>${h.label}</b><p>${h.reason}</p>`;const score=document.createElement('span');score.textContent=`${h.direction} · ${h.weight}分`;score.className=h.direction==='涨'?'up':'down';el.append(dot,body,score);box.append(el)})}
async function refreshPrice(){try{const[g,f]=await Promise.all([fetch('https://api.gold-api.com/price/XAU').then(r=>r.json()),fetch('https://open.er-api.com/v6/latest/USD').then(r=>r.json())]),cny=g.price*f.rates.CNY/31.1034768;document.querySelector('#cnyPrice').textContent=`¥${cny.toFixed(2)}`;document.querySelector('#priceDetail').textContent=`国际金价 $${g.price.toLocaleString()}/盎司 · USD/CNY ${f.rates.CNY.toFixed(4)} · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} 更新`}catch{document.querySelector('#priceDetail').textContent='实时价格暂时不可用，请稍后刷新'}}
function renderData(){const s=dataset.summary||{};document.querySelector('#settled').textContent=s.settled||0;document.querySelector('#pending').textContent=s.pending||0;document.querySelector('#neutral').textContent=s.neutral||0;document.querySelector('#accuracy').textContent=s.accuracy==null?'待结算':`${(s.accuracy*100).toFixed(1)}%`;document.querySelector('#hitRatio').textContent=s.settled?`${s.hits}/${s.settled}`:'尚无到期样本';document.querySelector('#dataTime').textContent=dataset.updatedAt?`数据 ${new Date(dataset.updatedAt).toLocaleString('zh-CN')} 更新`:'数据更新中';const ledger=document.querySelector('#ledger');ledger.innerHTML='';(dataset.predictions||[]).slice(0,6).forEach(p=>{const row=document.createElement('div');row.className='ledger-row';const body=document.createElement('div');const title=document.createElement('p');title.textContent=p.headline;const meta=document.createElement('small');meta.textContent=`预测 ${p.predictedDirection} · 入场 ¥${p.entryCnyGram.toFixed(2)} · ${p.status==='等待'?new Date(p.dueAt).toLocaleString('zh-CN')+' 到期':p.status}`;body.append(title,meta);const tag=document.createElement('span');tag.className='pill';tag.textContent=p.status;row.append(body,tag);ledger.append(row)});if(!ledger.children.length)ledger.textContent='正在建立第一批预测样本。';const list=document.querySelector('#newsList');list.innerHTML='';(dataset.items||[]).slice(0,8).forEach(item=>{const r=analyse(item.title),a=document.createElement('a');a.className='news-card';a.href=item.link;a.target='_blank';a.rel='noreferrer';const badge=document.createElement('span');badge.className=`pill ${r.direction==='涨'?'up':'down'}`;badge.textContent=r.hits.length?`${r.direction} · 强度 ${r.strength}`:'无强信号';const h=document.createElement('h3');h.textContent=item.title;const meta=document.createElement('div');meta.className='news-meta';const src=document.createElement('span');src.textContent=item.source;const time=document.createElement('span');time.textContent=new Date(item.publishedAt).toLocaleString('zh-CN');meta.append(src,time);a.append(badge,h,meta);list.append(a)})}
async function refreshData(){try{dataset=await fetch(`data.json?t=${Date.now()}`).then(r=>r.json());renderData()}catch{document.querySelector('#dataTime').textContent='预测数据暂时不可用'}}
document.querySelector('#newsInput').addEventListener('input',updateSignal);document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#newsInput').value=b.dataset.example;updateSignal()}));document.querySelector('#refresh').addEventListener('click',()=>{refreshPrice();refreshData()});updateSignal();refreshPrice();refreshData();setInterval(refreshPrice,120000);setInterval(refreshData,120000);
