const RULES=[
['降息预期','涨',3,'降低持有黄金的机会成本',/降息|鸽派|宽松|rate cuts?|dovish|yields? (?:fall|drop|retreat)/i],
['美元走弱','涨',3,'美元计价黄金获得支撑',/美元(?:下跌|走弱|回落)|dollar (?:falls|weakens|slides)/i],
['央行购金','涨',4,'结构性买盘增加',/央行(?:增持|购买|买入|购金)|central banks? (?:buy|add|boost).{0,20}gold/i],
['避险升温','涨',3,'不确定性推升避险需求',/战争|冲突升级|制裁|地缘政治|衰退|war|conflict escalat|sanctions?|geopolit|recession/i],
['通胀升温','涨',2,'购买力对冲需求可能上升',/通胀(?:上升|升温|超预期|反弹)|inflation (?:rises|heats|accelerates|above)/i],
['ETF流入','涨',3,'投资资金直接增加黄金需求',/黄金ETF(?:流入|增持)|资金流入黄金|gold (?:etf|fund).{0,16}(?:inflow|adds?)/i],
['加息预期','跌',3,'提高持有黄金的机会成本',/加息|鹰派|紧缩|收益率(?:上涨|上升|走高)|rate hikes?|hawkish|yields? (?:rise|climb|jump)/i],
['降息预期降温','跌',4,'利率可能在高位维持更久',/下调(?:美联储)?降息|推迟降息|rate.?cut (?:bets|odds|expectations) (?:fall|fade)|delay(?:ed)? rate cuts?/i],
['美元走强','跌',3,'美元计价黄金通常承压',/美元(?:上涨|走强)|dollar (?:rises|strengthens|gains)/i],
['风险缓和','跌',3,'避险溢价回落',/停火|和平协议|冲突缓和|软着陆|ceasefire|peace deal|conflict eases|soft landing/i],
['通胀降温','跌',2,'购买力对冲需求减弱',/通胀(?:下降|降温|低于预期)|inflation (?:falls|cools|below)/i],
['ETF流出','跌',3,'投资资金撤出黄金市场',/黄金ETF(?:流出|减持)|资金流出黄金|gold (?:etf|fund).{0,16}(?:outflow|cuts?)/i]
];
let dataset={items:[],summary:{settled:0,pending:0,neutral:0,hits:0,accuracy:null},predictions:[],priceHistory:[],updatedAt:null};
function analyse(text){const hits=RULES.filter(r=>r[4].test(text)).map(r=>({label:r[0],direction:r[1],weight:r[2],reason:r[3]}));const up=hits.filter(x=>x.direction==='涨').reduce((s,x)=>s+x.weight,0),down=hits.filter(x=>x.direction==='跌').reduce((s,x)=>s+x.weight,0),score=up-down,total=up+down,strength=total?Math.min(90,Math.round(20+Math.abs(score)/total*48+Math.min(total,12)*1.8)):0;return{hits,up,down,score,direction:score>=0?'涨':'跌',strength}}
function updateSignal(){const r=analyse(document.querySelector('#newsInput').value),dir=document.querySelector('#direction');dir.textContent=r.direction;dir.className=r.direction==='涨'?'up':'down';document.querySelector('#strength').textContent=r.strength;document.querySelector('#scoreline').textContent=`利多 ${r.up.toFixed(1)} 分 · 利空 ${r.down.toFixed(1)} 分`;document.querySelector('#netScore').textContent=`净分 ${r.score>0?'+':''}${r.score.toFixed(1)}`;const box=document.querySelector('#factors');box.innerHTML='';if(!r.hits.length){box.textContent='未命中明确规则，规则强度为 0。';return}r.hits.forEach(h=>{const el=document.createElement('div');el.className='factor';const dot=document.createElement('i');dot.style.background=h.direction==='涨'?'var(--up)':'var(--down)';const body=document.createElement('div');body.innerHTML=`<b>${h.label}</b><p>${h.reason}</p>`;const score=document.createElement('span');score.textContent=`${h.direction} · ${h.weight}分`;score.className=h.direction==='涨'?'up':'down';el.append(dot,body,score);box.append(el)})}
async function refreshPrice(){try{const[g,f]=await Promise.all([fetch('https://api.gold-api.com/price/XAU').then(r=>r.json()),fetch('https://open.er-api.com/v6/latest/USD').then(r=>r.json())]),cny=g.price*f.rates.CNY/31.1034768;document.querySelector('#cnyPrice').textContent=`¥${cny.toFixed(2)}`;document.querySelector('#priceDetail').textContent=`国际金价 $${g.price.toLocaleString()}/盎司 · USD/CNY ${f.rates.CNY.toFixed(4)} · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} 更新`}catch{document.querySelector('#priceDetail').textContent='实时价格暂时不可用，请稍后刷新'}}
const MACRO_LABELS=new Set(['降息预期','降息预期降温','美元走弱','美元走强','央行购金','通胀升温','通胀降温','加息预期']);
function clamp(value,min,max){return Math.min(max,Math.max(min,value))}
function component(net,total,max,fullAt){return total?max*(net/total)*Math.min(1,total/fullAt):0}
function signed(value){return`${value>0?'+':''}${value}`}
function deriveSentiment(){let macroNet=0,macroTotal=0,riskNet=0,riskTotal=0,relevant=0;const drivers=new Map(),now=Date.now();(dataset.items||[]).slice(0,12).forEach(item=>{const result=analyse(item.title);if(!result.hits.length)return;relevant++;const age=Math.max(0,(now-Date.parse(item.publishedAt))/3600000),recency=clamp(1-age/96,.35,1);result.hits.forEach(hit=>{const weight=hit.weight*recency*(hit.direction==='涨'?1:-1);drivers.set(hit.label,(drivers.get(hit.label)||0)+weight);if(MACRO_LABELS.has(hit.label)){macroNet+=weight;macroTotal+=Math.abs(weight)}else{riskNet+=weight;riskTotal+=Math.abs(weight)}})});const history=dataset.priceHistory||[],target=now-6*3600000,past=history.filter(point=>point.capturedAt<=target).sort((a,b)=>b.capturedAt-a.capturedAt)[0],momentum=past&&dataset.market?dataset.market.cnyGram-past.cnyGram:null,macro=component(macroNet,macroTotal,50,14),risk=component(riskNet,riskTotal,25,8),move=momentum==null?0:25*clamp(momentum/3.8,-1,1),score=Math.round(clamp(macro+risk+move,-100,100)),total=macroTotal+riskTotal,agreement=total?Math.abs(macroNet+riskNet)/total:0,confidenceScore=clamp(18+Math.min(relevant,6)*8+(momentum==null?0:15)+agreement*20,0,100),confidence=confidenceScore>=72?'较高':confidenceScore>=45?'中等':'较低',label=score>=60?'强烈偏多':score>=20?'偏多':score<=-60?'强烈偏空':score<=-20?'偏空':'中性';return{score,label,confidence,relevant,macro:Math.round(macro),risk:Math.round(risk),momentum:Math.round(move),hours:past?Math.max(1,Math.round((now-past.capturedAt)/3600000)):null,drivers:[...drivers.entries()].sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,3).map(([name,value])=>`${name}${value>=0?'利多':'利空'}`)}}
function renderSentiment(){const s=deriveSentiment(),label=document.querySelector('#sentimentLabel');label.textContent=s.label;label.className=s.score>19?'up':s.score<-19?'down':'';document.querySelector('#sentimentScore').textContent=`${signed(s.score)} / 100`;document.querySelector('#sentimentConfidence').textContent=`置信度${s.confidence} · 命中${s.relevant}条有效新闻 · ${s.hours?`${s.hours}小时价格动量`:'价格历史积累中'}`;document.querySelector('#sentimentMarker').style.left=`${(s.score+100)/2}%`;[['macroScore',s.macro],['riskScore',s.risk],['momentumScore',s.momentum]].forEach(([id,value])=>{const el=document.querySelector(`#${id}`);el.textContent=signed(value);el.className=value>0?'up':value<0?'down':''});document.querySelector('#sentimentDrivers').textContent=`主要驱动：${s.drivers.join(' · ')||'暂无方向一致的有效信号'}`}
function renderData(){renderSentiment();const s=dataset.summary||{};document.querySelector('#settled').textContent=s.settled||0;document.querySelector('#pending').textContent=s.pending||0;document.querySelector('#neutral').textContent=s.neutral||0;document.querySelector('#accuracy').textContent=s.accuracy==null?'待结算':`${(s.accuracy*100).toFixed(1)}%`;document.querySelector('#hitRatio').textContent=s.settled?`${s.hits}/${s.settled}`:'尚无到期样本';document.querySelector('#dataTime').textContent=dataset.updatedAt?`数据 ${new Date(dataset.updatedAt).toLocaleString('zh-CN')} 更新`:'数据更新中';const ledger=document.querySelector('#ledger');ledger.innerHTML='';(dataset.predictions||[]).slice(0,6).forEach(p=>{const row=document.createElement('div');row.className='ledger-row';const body=document.createElement('div');const title=document.createElement('p');title.textContent=p.headline;const meta=document.createElement('small');meta.textContent=`预测 ${p.predictedDirection} · 入场 ¥${p.entryCnyGram.toFixed(2)} · ${p.status==='等待'?new Date(p.dueAt).toLocaleString('zh-CN')+' 到期':p.status}`;body.append(title,meta);const tag=document.createElement('span');tag.className='pill';tag.textContent=p.status;row.append(body,tag);ledger.append(row)});if(!ledger.children.length)ledger.textContent='正在建立第一批预测样本。';const list=document.querySelector('#newsList');list.innerHTML='';(dataset.items||[]).slice(0,8).forEach(item=>{const r=analyse(item.title),a=document.createElement('a');a.className='news-card';a.href=item.link;a.target='_blank';a.rel='noreferrer';const badge=document.createElement('span');badge.className=`pill ${r.direction==='涨'?'up':'down'}`;badge.textContent=r.hits.length?`${r.direction} · 强度 ${r.strength}`:'无强信号';const h=document.createElement('h3');h.textContent=item.title;const meta=document.createElement('div');meta.className='news-meta';const src=document.createElement('span');src.textContent=item.source;const time=document.createElement('span');time.textContent=new Date(item.publishedAt).toLocaleString('zh-CN');meta.append(src,time);a.append(badge,h,meta);list.append(a)})}
async function refreshData(){try{dataset=await fetch(`data.json?t=${Date.now()}`).then(r=>r.json());renderData()}catch{document.querySelector('#dataTime').textContent='预测数据暂时不可用'}}
document.querySelector('#newsInput').addEventListener('input',updateSignal);document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#newsInput').value=b.dataset.example;updateSignal()}));document.querySelector('#refresh').addEventListener('click',()=>{refreshPrice();refreshData()});updateSignal();refreshPrice();refreshData();setInterval(refreshPrice,120000);setInterval(refreshData,120000);
